const GridData = [
  {
    number: 1,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 2,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 3,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 4,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 5,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 6,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 7,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 8,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 9,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 10,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 11,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 12,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 13,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 14,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 15,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 16,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 17,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 18,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 19,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 20,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 21,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 22,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 23,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 24,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 25,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 26,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 27,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 28,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 29,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 30,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 31,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 32,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 33,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 34,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 35,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 36,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 37,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 38,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 39,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 40,
    color: "#43a9e0",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 41,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 42,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 43,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 44,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 45,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 46,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 47,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 48,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 49,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 50,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 51,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 52,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 53,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 54,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 55,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 56,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 57,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 58,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 59,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 60,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 61,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 62,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 63,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 64,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 65,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 66,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 67,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 68,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 69,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 70,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 71,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 72,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 73,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 74,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 75,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 76,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 77,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 78,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 79,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
  {
    number: 80,
    color: "#d30d17",
    topFive: false,
    selected: false,
    usage: 0,
  },
];

export default GridData;
